BADGES_TARGET = niv1__taille_chaine niv1__inverse_chaine niv1__tri_min niv2__inverse_liste niv2__decoupe_liste niv3__palin
BINS = struct double_rect


COMMON := ../common
include $(COMMON)/rules.mk


inverse_liste: inverse_liste.o fct_inverse_liste.o

decoupe_liste: decoupe_liste.o fct_decoupe_liste.o

palin: palin.o fct_palin.o

taille_chaine: taille_chaine.o fct_taille_chaine.o

inverse_chaine: inverse_chaine.o fct_inverse_chaine.o

struct: struct.o fct_struct.o

double_rect: double_rect.o fct_double_rect.o

tri_min: tri_min.o fct_tri_min.o
